import { Source_Code_Pro } from 'next/font/google';
import './globals.css';

// components
import Header from '@/components/Header';
import PageTransition from '@/components/PageTransition';
import StairEffect from '@/components/StairEffect';


const sourceCodePro = Source_Code_Pro({
  subsets: ['latin'],
  weight: ['200', '300', '400', '500', '600', '700', '800', '900'],
});
variable: '--font-sourceCodePro';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      
      <body className={sourceCodePro.variable}>
        <Header />
        <StairEffect />
        <PageTransition>{children}</PageTransition> 
        
       

      </body>
    </html>
  );
}
